# Generated by Django 4.0.2 on 2022-02-21 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.manufacturer'),
            preserve_default=False,
        ),
    ]
