# Generated by Django 4.0.2 on 2022-02-21 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_station_chargebox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargebox',
            options={'verbose_name_plural': 'Chargeboxes'},
        ),
    ]
