# Generated by Django 4.0.2 on 2022-02-22 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chargebox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Chargeboxes',
            },
        ),
        migrations.CreateModel(
            name='Install',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.customer')),
                ('manufacturer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Evse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evse_id', models.CharField(max_length=6)),
                ('chargebox_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.chargebox')),
            ],
        ),
        migrations.AddField(
            model_name='chargebox',
            name='install_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.install'),
        ),
    ]
